export const imageSlots = [
  ["hero.image", "Hero — main image"], ["services.hotel_image", "Services — pet hotel"],
  ["services.puppies_image", "Services — puppies"], ["services.grooming_image", "Services — grooming"],
  ["services.shop_image", "Services — pet shop"], ["hotel.dogs_image", "Hotel — dog rooms"],
  ["hotel.cats_image", "Hotel — cat rooms"], ["hotel.wash_image", "Hotel — premium wash"],
  ["gallery.featured", "Gallery — featured"], ["gallery.image_2", "Gallery — image 2"],
  ["gallery.image_3", "Gallery — image 3"], ["gallery.image_4", "Gallery — image 4"],
  ["gallery.image_5", "Gallery — image 5"], ["gallery.image_6", "Gallery — image 6"],
  ["gallery.image_7", "Gallery — image 7"], ["gallery.image_8", "Gallery — image 8"],
  ["story.kumi_image", "Our story — Kumi"], ["team.banner_image", "Team — banner"],
] as const;

export const imageSlotDefaults: Record<string, string> = {
  "hero.image": "/assets/photos/shiba-smile.webp",
  "services.hotel_image": "/assets/photos/hotel-rooms.webp",
  "services.puppies_image": "/assets/photos/shiba-sit.webp",
  "services.grooming_image": "/assets/photos/grooming-area.webp",
  "services.shop_image": "/assets/photos/store-interior.webp",
  "hotel.dogs_image": "/assets/photos/hotel-rooms-3.webp",
  "hotel.cats_image": "/assets/photos/hotel-rooms-2.webp",
  "hotel.wash_image": "/assets/photos/grooming-station.webp",
  "gallery.featured": "/assets/photos/storefront.webp",
  "gallery.image_2": "/assets/photos/team-inside.webp",
  "gallery.image_3": "/assets/photos/hotel-rooms.webp",
  "gallery.image_4": "/assets/photos/grooming-area.webp",
  "gallery.image_5": "/assets/photos/food-aisle.webp",
  "gallery.image_6": "/assets/photos/reception-cctv.webp",
  "gallery.image_7": "/assets/photos/shiba-aisle.webp",
  "gallery.image_8": "/assets/photos/carriers.webp",
  "story.kumi_image": "/assets/photos/shiba-kumi.webp",
  "team.banner_image": "/assets/photos/team-group.webp",
};
