-- Run once in Supabase > SQL Editor after schema.sql.
-- This is additive and does not remove any earlier operational tables.
create table if not exists public.staff_records (
  id bigint generated by default as identity primary key,
  record_type text not null check (record_type in ('agreement','checklist')),
  record_status text not null default 'completed' check (record_status in ('completed')),
  customer_name text not null default '', pet_name text not null default '',
  record_data jsonb not null default '{}'::jsonb,
  signature_path text, signature_hash text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
create index if not exists staff_records_type_idx on public.staff_records(record_type);
create index if not exists staff_records_customer_idx on public.staff_records(customer_name);
create index if not exists staff_records_pet_idx on public.staff_records(pet_name);
create index if not exists staff_records_updated_idx on public.staff_records(updated_at desc);
alter table public.staff_records enable row level security;
revoke all on public.staff_records from anon, authenticated;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('staff-signatures','staff-signatures',false,2097152,array['image/jpeg'])
on conflict (id) do update set public=false,file_size_limit=2097152,allowed_mime_types=array['image/jpeg'];
-- No browser policies: all operations are server-side after staff verification.
