import { requireStaff } from "../../../lib/staff-auth";
import { createAdminClient } from "../../../lib/supabase/admin";

type StaffRecord={id:number;record_type:string;record_data:Record<string,unknown>;created_at:string;updated_at:string;signature_hash:string};
const esc=(s:string)=>s.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)").replace(/[^\x20-\x7e]/g,"-");
const xml=(s:string)=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function lines(r:StaffRecord){const out=[r.record_type==="agreement"?"Confidentiality Agreement":"Daily Checklist",`Record #${r.id}`,`Created: ${r.created_at}`,`Updated: ${r.updated_at}`,""];for(const [k,v] of Object.entries(r.record_data||{})){if(k==="daily_rows")continue;if(v!=="")out.push(`${k.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}: ${Array.isArray(v)?v.join(", "):v}`)}const rows=r.record_data?.daily_rows;if(Array.isArray(rows)&&rows.length){out.push("","Daily Care Log");rows.forEach((row,i)=>out.push(`Entry ${i+1} - ${Object.entries(row as object).filter(([,v])=>v).map(([k,v])=>`${k.replaceAll("_"," ")}: ${v}`).join(" | ")}`));}if(r.signature_hash)out.push("","Electronic signature attached",`Signature SHA-256: ${r.signature_hash}`);return out.flatMap(s=>{const t=String(s);return t? t.match(/.{1,88}(?:\s|$)|.{1,88}/g)?.map(x=>x.trimEnd())||[t]:[""]});}
function pdf(records:StaffRecord[]){const pages=records.flatMap(r=>{const a=lines(r);const p=[];for(let i=0;i<a.length;i+=45)p.push(a.slice(i,i+45));return p});const objs:string[]=[];objs[1]="<< /Type /Catalog /Pages 2 0 R >>";objs[3]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";const pageIds:number[]=[];let n=4;for(const page of pages){const pid=n++,cid=n++;pageIds.push(pid);let stream="BT\n/F1 10 Tf\n50 790 Td\n14 TL\n";page.forEach((line,i)=>{if(i)stream+="T*\n";stream+=`(${esc(line)}) Tj\n`});stream+="ET";objs[pid]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${cid} 0 R >>`;objs[cid]=`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`;}objs[2]=`<< /Type /Pages /Kids [ ${pageIds.map(x=>`${x} 0 R`).join(" ")} ] /Count ${pageIds.length} >>`;let output="%PDF-1.4\n";const offsets:number[]=[0];for(let i=1;i<objs.length;i++){offsets[i]=Buffer.byteLength(output);output+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=Buffer.byteLength(output);output+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)output+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;output+=`trailer << /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output);}
function crc32(buf:Buffer){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(files:{name:string;data:Buffer}[]){const local:Buffer[]=[];const central:Buffer[]=[];let offset=0;for(const f of files){const name=Buffer.from(f.name),crc=crc32(f.data);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt32LE(crc,14);h.writeUInt32LE(f.data.length,18);h.writeUInt32LE(f.data.length,22);h.writeUInt16LE(name.length,26);local.push(h,name,f.data);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(f.data.length,20);ch.writeUInt32LE(f.data.length,24);ch.writeUInt16LE(name.length,28);ch.writeUInt32LE(offset,42);central.push(ch,name);offset+=h.length+name.length+f.data.length;}const cb=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cb.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,cb,end]);}
function docx(r:StaffRecord){const paras=lines(r).map(s=>`<w:p><w:r><w:t xml:space="preserve">${xml(s)}</w:t></w:r></w:p>`).join("");const files=[{name:"[Content_Types].xml",data:Buffer.from('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>')},{name:"_rels/.rels",data:Buffer.from('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>')},{name:"word/document.xml",data:Buffer.from(`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paras}<w:sectPr/></w:body></w:document>`)}];return zip(files);}

export async function GET(request:Request){await requireStaff();const url=new URL(request.url);const format=url.searchParams.get("format");const ids=[...new Set((url.searchParams.get("ids")||"").split(",").filter(x=>/^\d+$/.test(x)).slice(0,500))];if(!ids.length||!(["pdf","docx"].includes(format||"")))return new Response("Select at least one valid record.",{status:400});const {data,error}=await createAdminClient().from("staff_records").select("id,record_type,record_data,created_at,updated_at,signature_hash").in("id",ids).order("id");if(error||!data?.length)return new Response("No records found.",{status:404});let bytes:Buffer,name:string,mime:string;if(format==="pdf"){bytes=pdf(data as StaffRecord[]);name=data.length===1?`pet-record-${data[0].id}.pdf`:`pet-records-${new Date().toISOString().slice(0,10)}.pdf`;mime="application/pdf";}else if(data.length===1){bytes=docx(data[0] as StaffRecord);name=`pet-record-${data[0].id}.docx`;mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document";}else{bytes=zip(data.map(r=>({name:`pet-record-${r.id}.docx`,data:docx(r as StaffRecord)})));name=`pet-records-${new Date().toISOString().slice(0,10)}.zip`;mime="application/zip";}return new Response(new Uint8Array(bytes),{headers:{"Content-Type":mime,"Content-Disposition":`attachment; filename="${name}"`,"Cache-Control":"private, no-store"}});}
