import Link from "next/link";
import { saveRecord } from "./actions";
import SignaturePad from "./signature-pad";
import styles from "./staff.module.css";

export type RecordData = Record<string, string | string[] | Record<string,string>[]>;
const val = (data: RecordData, key: string) => typeof data[key] === "string" ? data[key] as string : "";
function Field({ data, name, label, type="text", required=false, span=false }: { data: RecordData; name:string; label:string; type?:string; required?:boolean; span?:boolean }) {
  return <label className={`${styles.field} ${span ? styles.span2 : ""}`}><span>{label}{required ? " *" : ""}</span><input name={name} type={type} defaultValue={val(data,name)} required={required} /></label>;
}
function Textarea({ data, name, label }: { data:RecordData; name:string; label:string }) { return <label className={`${styles.field} ${styles.full}`}><span>{label}</span><textarea name={name} rows={4} defaultValue={val(data,name)} /></label>; }
function FormEnd({ editing, data, signatureUrl }: { editing:boolean; data:RecordData; signatureUrl?:string }) { return <><SignaturePad existingUrl={signatureUrl}/><div className={styles.grid}><Field data={data} name="signer_name" label="Customer Name / Printed Name" required/><Field data={data} name="signed_date" label="Date Signed" type="date" required/></div><div className={styles.actions}><button className={`${styles.btn} ${styles.primary}`} type="submit">{editing ? "Update Record" : "Save Record"}</button><Link className={styles.btn} href="/staff">Cancel</Link></div></>; }

export function AgreementForm({ id, data, signatureUrl }: { id?:string; data:RecordData; signatureUrl?:string }) {
  const services = Array.isArray(data.services) ? data.services as string[] : [];
  return <section className={styles.card}><div className={styles.title}><div><span className={styles.kicker}>Form 01</span><h2>Confidentiality Agreement</h2></div><span className={styles.badge}>{id ? `Editing #${id}` : "New record"}</span></div>
    <form action={saveRecord} className={styles.form}><input type="hidden" name="record_type" value="agreement"/><input type="hidden" name="record_id" value={id || ""}/>
      <h3>Customer Information</h3><div className={styles.grid}><Field data={data} name="customer_name" label="Name" required/><Field data={data} name="phone" label="Phone Number" type="tel" required/><Field data={data} name="email" label="Email" type="email"/><Field data={data} name="address" label="Address" span/></div>
      <h3>Pet Information</h3><div className={styles.grid}><Field data={data} name="pet_name" label="Pet Name" required/><Field data={data} name="pet_type" label="Type"/><Field data={data} name="breed" label="Breed"/><Field data={data} name="color" label="Color"/><Field data={data} name="age" label="Age"/><Field data={data} name="weight" label="Weight"/><Field data={data} name="special_needs" label="Special Instructions / Needs" span/></div>
      <h3>Service Details</h3><div className={styles.checks}>{["Grooming","Pet Boarding","Pet Sitting","Others"].map(s=><label key={s}><input type="checkbox" name="services" value={s} defaultChecked={services.includes(s)}/> {s}</label>)}</div>
      <Textarea data={data} name="additional_notes" label="Additional Notes"/>
      <div className={styles.terms}><h3>Agreement</h3><p>Confidential information includes all information disclosed by the Pet Shop to the Client, whether written, oral, electronic, or otherwise, that is designated as confidential or should reasonably be understood to be confidential.</p><ol><li><strong>Customer obligations:</strong> Maintain confidential information in strict confidence, do not disclose it without prior written consent, and use it only for its intended purpose.</li><li><strong>Precautions:</strong> Take reasonable steps to prevent unauthorized access, use, or disclosure.</li><li><strong>Prohibitions:</strong> Do not post negative feedback or reviews on social media, websites, or forums, and do not engage in badmouthing, gossip, defamation, or negative discussion about the Pet Shop.</li><li><strong>Acknowledgment of harm:</strong> Unauthorized disclosure or use may cause irreparable harm and may entitle the Pet Shop to legal remedies.</li><li><strong>Limitation on civil liability:</strong> Civil liability for damages is limited to the amount entered below.</li><li><strong>Governing law:</strong> Republic of the Philippines.</li><li><strong>Entire agreement:</strong> This agreement supersedes prior discussions or understandings concerning its subject matter.</li></ol></div>
      <Field data={data} name="liability_limit" label="Civil Liability Limit (PHP)" type="number"/><FormEnd editing={!!id} data={data} signatureUrl={signatureUrl}/>
    </form></section>;
}

const daily = [["date","Date","date"],["time","Time","time"],["morning_food","Morning Food","text"],["afternoon_food","Afternoon Food","text"],["evening_food","Evening Food","text"],["snack","Snack","text"],["fresh_water","Fresh Water","text"],["vitamins","Vitamins","text"],["potty_time","Potty Time","text"],["room_clean","Room Clean","text"],["room_sanitation","Room Sanitation","text"],["staff_assisted","Staff Assisted","text"]];
export function ChecklistForm({ id, data, signatureUrl }: { id?:string; data:RecordData; signatureUrl?:string }) {
  const rows = Array.isArray(data.daily_rows) ? data.daily_rows as Record<string,string>[] : [];
  return <section className={styles.card}><div className={styles.title}><div><span className={styles.kicker}>Form 02</span><h2>Daily Pet Hotel Checklist</h2></div><span className={styles.badge}>{id ? `Editing #${id}` : "New record"}</span></div>
    <form action={saveRecord} className={styles.form}><input type="hidden" name="record_type" value="checklist"/><input type="hidden" name="record_id" value={id || ""}/><div className={styles.grid}><Field data={data} name="pet_name" label="Pet's Name" required/><Field data={data} name="breed" label="Breed"/><Field data={data} name="room" label="Room"/><Field data={data} name="checkin_date" label="Check-in Date" type="date" required/><Field data={data} name="checkin_time" label="Check-in Time" type="time"/><Field data={data} name="checkout_date" label="Check-out Date" type="date"/><Field data={data} name="checkout_time" label="Check-out Time" type="time"/></div><Textarea data={data} name="special_instructions" label="Special Instructions"/>
      <h3>Daily Care Log</h3><div className={styles.tableWrap}><table className={styles.daily}><thead><tr>{daily.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{Array.from({length:10},(_,i)=><tr key={i}>{daily.map(([key,label,type])=><td key={key} data-label={label}><input aria-label={`${label} row ${i+1}`} type={type} name={`daily_${i}_${key}`} defaultValue={rows[i]?.[key] || ""}/></td>)}</tr>)}</tbody></table></div>
      <div className={styles.terms}><h3>Consent</h3><p>I authorize Shiba Inu Pet Shop veterinarians and staff to perform procedures necessary for the health, safety, and well-being of my pet while under their care and supervision. The attending veterinarian is not liable for injury or death from risks beyond their control.</p><p>If my pet is lost from force majeure, theft, or an attempt to escape, becomes ill, or dies while in the studio or during grooming, I will not hold Shiba Inu Pet Shop responsible. If my pet continues to cry, bark, or is ready for release and cannot be collected, the shop may arrange authorized transport at the owner&apos;s expense. I understand and accept that any debt owed for accountable loss will be paid.</p></div>
      <Field data={data} name="customer_name" label="Pet Owner / Authorized Person" required/><FormEnd editing={!!id} data={data} signatureUrl={signatureUrl}/>
    </form></section>;
}
